# Generated by Django 3.0.2 on 2020-02-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200207_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
