# Generated by Django 3.0.2 on 2020-02-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_is_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': ('add', 'change', 'view')},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'default_permissions': ('add', 'change', 'view')},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': ('add', 'view')},
        ),
    ]
