# Generated by Django 3.0.2 on 2020-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200207_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
