# Generated by Django 3.0.2 on 2020-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_purchase_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock_threshold',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
